import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [price, setPrice] = useState(21000);
  const [BTCValue, setBTCValue] = useState("");

  const handleUSDChange = (event) => {
    console.log({ usd: event.target.value });
    const USD = Number(event.target.value);
    const valueInBTC = Number(USD / price).toFixed(8);
    setBTCValue(valueInBTC);
  };

  useEffect(() => {
    const getPrice = async () => {
      const response = await axios.get(
        "https://rest.coinapi.io/v1/exchangerate/BTC/USD",
        {
          headers: { "X-CoinAPI-Key": "A38D9B49-A2EA-49D5-A5C2-FDF007C180A4" },
        }
      );
      const data = response.data;
      console.log({ data });
      setPrice(Number(Number(data.rate).toFixed(0)));
    };

    getPrice();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Price of BTC: ${price}</h1>
        <input
          className={styles.input}
          type="number"
          placeholder="input amount in USD"
          onChange={handleUSDChange}
        />
        <input
          value={BTCValue}
          className={styles.input}
          disabled
          placeholder="value in BTC"
        />
      </main>
    </div>
  );
}
