import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Okra from "okra-js";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  function connectViaOptions() {
    Okra.buildWithOptions({
      name: "VeendHQ",
      env: "production-sandbox",
      key: "62138db2-f3f1-5322-ba67-f1d8855ad2d2",
      token: "610c8029636246391da3be68",
      source: "link",
      color: "#060089",
      limit: "24",
      callback_url: "",
      redirect_url: "",
      currency: "NGN",
      logo: "https://dash.okra.ng/static/media/OkraFullLogo.4bc5f093.png",
      onSuccess: function (data: {}) {
        console.log("success", data);
      },
      onClose: function () {
        console.log("closed");
      },
    });
  }

  function connectViaCode() {
    Okra.buildWithShortUrl({
      short_url: "J74ThThX2",
      onSuccess: function (data: {}) {
        console.log("success", data);
      },
      onClose: function () {
        console.log("closed");
      },
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <button className={styles.card} onClick={connectViaOptions}>
            <h2>Link with Okra &rarr;</h2>
            <p>
              Instantly link your bank details with Okra and verified in
              minutes.
            </p>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
